{- | additional parameters: ifqr, iamp1, irate

In this instrument we find a RANDI unit generator at the place usually occupied
by the envelope. The center frequency of the noise band generated by RANDI varies 
with the pitch of the wave oscillator.

The pitch control function works exactly as in instrument Whiny.hs; except that irate
is now duration independent. Function table f33 is scanned at a rate of 3 Hz for 6.5 
seconds, repeating a frequency descent of two octaves. We want to leave it for further 
experimentation to the reader to find out more about the glissando of a pitched noise 
band. The sounds unpleasantly remind us of certain noise pollutions.

The bad cutoffs can be eliminated by supplying an envelope. (Risset 1969: #511)
-}
module Cheap where

import Csound

instr :: (Iamp, Icps, Icps, Icps) -> SE Sig
instr (amp, randCps, cps, lfoCps) = do
    env <- randi (sig amp) (sig randCps)
    return $ env * oscBy (sines [1]) (sig cps * oscBy twoOctsDown (sig lfoCps))
    where twoOctsDown = lins [0.999, 20, 0.999, 500, 0.235, 20, 0.235]

res = sco instr $ delay 1 $ chord [
    6.5 *| temp (0.5, 80, 1000, 3),
    delay 2 $ 6.5 *| temp (0.5, 150, 750, 3)]
    
--main = writeCsd "tmp.csd" res
main = totem res
    
    
